# Generated by Django 4.0.5 on 2022-06-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='note',
            field=models.TextField(),
        ),
    ]
